on: [push]

name: Build Release

jobs:
  build_and_test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: apt install libxcb-composite0-dev libx11-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
